---
title: "plots ratings categories"
output: html_document
---

```{r}
rm(list=ls())
data <- read.csv("aut_fork_rated(1).csv")
library(ggplot2)
library(dplyr)
```
ggplot(datforplot, aes(x=factor(originality_rater01)))+
  geom_bar(stat="bin", width=0.7, fill="steelblue")+
  theme_minimal()
```{r}
datforplot <- data %>% select(respondent_id, originality_rater01, utility_rater01, surprise_rater01, human)
datforplot$Group <- ifelse(datforplot$human == 0, "GPT-3", "Human")

orig <- datforplot %>% group_by(Group) %>% select(originality_rater01) %>% table()
orig <- data.frame(t(orig))


ggplot(orig, aes(x = originality_rater01, y = Freq, fill = Group)) +
  geom_col(position = "dodge") + labs(title = "Originality") + labs(x = "Score")


util <- datforplot %>% group_by(Group) %>% select(utility_rater01) %>% table()
util <- data.frame(t(util))

ggplot(util, aes(x = utility_rater01, y = Freq, fill = Group)) +
  geom_col(position = "dodge") + labs(title = "Utility") + labs(x = "Score")


surp <- datforplot %>% group_by(Group) %>% select(surprise_rater01) %>% table()
surp <- data.frame(t(surp))

ggplot(surp, aes(x = surprise_rater01, y = Freq, fill = Group)) +
  geom_col(position = "dodge")+ labs(title = "Surprise") + labs(x = "Score")


table(datforplot$human)

unique(datforplot$respondent_id[datforplot$human == 0]) %>% length()
```


```{r}
cat <- read.csv("GPT3_fork_cat_num_categories.csv")
cat <- cat %>% select(-1)
cat

ggplot(cat, aes(num_categories, fill=as.factor(human))) + theme_classic() +
  geom_histogram(
    alpha=0.2, color="gray80",
    position="identity")

cat$Group <- ifelse(cat$human == 0, "GPT-3", "Human")

ggplot(cat, aes(x=num_categories))+
  geom_histogram(aes(y=..density..,fill=Group),color="grey80", binwidth = 1)+
  facet_grid(as.factor(Group)~.) + labs(title = "Categories") + labs(x = "Number of categories per respondent")
ggplot(cat, aes(x=num_categories))+
  geom_histogram(aes(y=..density..,fill=Group),color="grey80", binwidth = .5)+
  facet_grid(as.factor(Group)~.) + labs(title = "Categories") + labs(x = "Number of categories per respondent")


cat2 <- cat %>% group_by(Group) %>% select(num_categories) %>% table()
cat2 <- data.frame(t(cat2))
ggplot(cat2, aes(x = num_categories, y = Freq, fill = Group)) +
  geom_col(position = "dodge") + labs(title = "Categories") + labs(x = "Number of categories per respondent")
```
